function getIndexMenuJson(grade) {
	var menuJson;
	if (grade == 1) {
		menuJson = "[{"
				+ "\"name\": \"系统设置\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"导航设置\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=58&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"单价设置\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=28&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"年份设置\","
				+ "\"url\":\"sysmng.report.do?subSys=gaokao&repID=72&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"规则设置\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=60&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"客服设置\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"密码设置\","
				+ "\"url\":\"/sysmng.initForm.do?subSys=sysmng&formID=3\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"信息管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"栏目管理\","
				+ "\"url\":\"getp_lqfs.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"高校信息管理\","
				+ "\"url\":\"getp_zyfs.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专业信息管理\","
				+ "\"url\":\"getyx.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"省控线管理\","
				+ "\"url\":\"/zy/index2.html\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"分数线管理\","
				+ "\"url\":\"sysmng.report.do?subSys=gaokao&repID=21&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"代理管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"区域管理\","
				+ "\"url\":\"http://gklqzn.com/zhiyeku/hulianwangIT/\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"级别管理\","
				+ "\"url\":\"http://gklqzn.com/mbti.php\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"代理管理\","
				+ "\"url\":\"http://gklqzn.com/93mbti.php\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"用户管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"生成用户号段\","
				+ "\"url\":\"getp.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"号段管理\","
				+ "\"url\":\"get_hjx.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"分配号段\","
				+ "\"url\":\"getp_mc.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"用户管理\","
				+ "\"url\":\"getp_zy.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"消费统计\","
				+ "\"url\":\"getp_xymc.jsp\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"财务中心\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"订单管理\","
				+ "\"url\":\"getp_lqfs.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"结算处理\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"结算统计\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"退款管理\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"退款统计\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"日志中心\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"登陆日志\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=1\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"操作日志\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=2\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"专家管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"专家管理\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=85\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"订单统计\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=84\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"服务管理\","
				+ "\"url\":\"/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"价格管理\","
				+ "\"url\":\"/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"操作手册\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"总后台\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=88&isQuery=1&isShowCnd=1\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"代理后台\","
				+ "\"url\":\"http://ly.9fsystem.com/sc.swf\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"用户后台\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=37&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专家后台\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=37&isTopBar=0\","
				+ "\"target\":\"workspace\"}]}]";
	} else if (grade == 2) {
		menuJson = "[{"
				+ "\"name\": \"系统设置\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"我的信息\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=58&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"单价设置\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=28&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"年份设置\","
				+ "\"url\":\"sysmng.report.do?subSys=gaokao&repID=72&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"规则设置\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=60&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"客服设置\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"密码设置\","
				+ "\"url\":\"/sysmng.initForm.do?subSys=sysmng&formID=3\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"信息管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"栏目管理\","
				+ "\"url\":\"getp_lqfs.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"高校信息管理\","
				+ "\"url\":\"getp_zyfs.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专业信息管理\","
				+ "\"url\":\"getyx.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"省控线管理\","
				+ "\"url\":\"/zy/index2.html\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"分数线管理\","
				+ "\"url\":\"sysmng.report.do?subSys=gaokao&repID=21&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"代理管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"区域管理\","
				+ "\"url\":\"http://gklqzn.com/zhiyeku/hulianwangIT/\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"级别管理\","
				+ "\"url\":\"http://gklqzn.com/mbti.php\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"代理管理\","
				+ "\"url\":\"http://gklqzn.com/93mbti.php\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"用户管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"生成用户号段\","
				+ "\"url\":\"getp.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"号段管理\","
				+ "\"url\":\"get_hjx.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"分配号段\","
				+ "\"url\":\"getp_mc.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"用户管理\","
				+ "\"url\":\"getp_zy.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"消费统计\","
				+ "\"url\":\"getp_xymc.jsp\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"财务中心\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"订单管理\","
				+ "\"url\":\"getp_lqfs.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"结算处理\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"结算统计\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"退款管理\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"退款统计\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"日志中心\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"登陆日志\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=1\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"操作日志\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=2\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"专家管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"专家管理\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=85\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"订单统计\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=84\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"服务管理\","
				+ "\"url\":\"/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"价格管理\","
				+ "\"url\":\"/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"操作手册\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"总后台\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=88&isQuery=1&isShowCnd=1\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"代理后台\","
				+ "\"url\":\"http://ly.9fsystem.com/sc.swf\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"用户后台\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=37&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专家后台\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=37&isTopBar=0\","
				+ "\"target\":\"workspace\"}]}]";
	} else if (grade == 3) {
		menuJson = "[{"
				+ "\"name\": \"代理管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"分级代理\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=85\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"公司级用户卡管理\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=84\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"代理商推广码\","
				+ "\"url\":\"/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"用户管理\","
				+ "\"url\":\"/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专家服务管理\","
				+ "\"url\":\"/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]}]";
	} else if (grade == 4) {
		menuJson = "[{"
				+ "\"name\": \"个人中心\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"个人资料\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=58&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"我的成绩\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=28&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"我的志愿表\","
				+ "\"url\":\"sysmng.report.do?subSys=gaokao&repID=72&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"备选院校\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=60&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"常见问题\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"密码设置\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.initForm.do?subSys=sysmng&formID=3\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"联系客服\","
				+ "\"url\":\"sysmng.initInsert.do?subSys=gaokao&insertID=insTb\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"我的推广码\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"数据信息查询\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"院校录取分数查询\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=49&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专业录取分数查询\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=52&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"院校查询\","
				+ "\"url\":\"getyx.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专业解析\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=21&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"招生计划招生简章查询\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"历史省控线查询\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"职业规划\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"职业查询\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"职业倾向测评简易版\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"职业倾向测评专业版\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"考前模拟填报\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"投档线预测法择校\","
				+ "\"url\":\"getp.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"黄金录取线预测法择校\","
				+ "\"url\":\"get_hjx.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"名次法择校\","
				+ "\"url\":\"getp_mc.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"按专业择校\","
				+ "\"url\":\"getp_zy.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"心仪院校测算（名次预测）\","
				+ "\"url\":\"getp_xymc.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"心仪院校预测（分数测算）\","
				+ "\"url\":\"getp_xyfs.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"志愿模拟填报\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"考后智能填报\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"院校投档线预测\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"院校黄金录取线预测\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"院校专业录取线预测\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"按投档线择校\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"按黄金录取线择校\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"名次法择校\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"按专业择校\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"心仪院校测算（按名次）\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"心仪院校预测（按分数）\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"智能志愿填报\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"志愿表智能审核\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"报考课堂\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"电子书刊\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=1\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"视频讲座\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=2\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"实战指南\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=3\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"代理管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"分级代理\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=85\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"公司级用户卡管理\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=84\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"代理商推广码\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"用户管理\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专家服务管理\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"系统管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"各省份充值设置\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=88&isQuery=1&isShowCnd=1\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"在线帮助\","
				+ "\"url\":\"http://ly.9fsystem.com/sc.swf\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"历年省控线\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=37&isTopBar=0\","
				+ "\"target\":\"workspace\"}]}]";
	} else if (grade == 5) {
		menuJson = "[{"
				+ "\"name\": \"个人中心\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"个人资料\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=58&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"我的成绩\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=28&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"我的志愿表\","
				+ "\"url\":\"sysmng.report.do?subSys=gaokao&repID=72&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"备选院校\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=60&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"常见问题\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"密码设置\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.initForm.do?subSys=sysmng&formID=3\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"联系客服\","
				+ "\"url\":\"sysmng.initInsert.do?subSys=gaokao&insertID=insTb\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"我的推广码\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"数据信息查询\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"院校录取分数查询\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=49&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专业录取分数查询\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=52&isTopBar=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"院校查询\","
				+ "\"url\":\"getyx.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专业解析\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=21&isQuery=1&isShowCnd=1&isAutoHideCnd=0\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"招生计划招生简章查询\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"历史省控线查询\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"职业规划\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"职业查询\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"职业倾向测评简易版\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"职业倾向测评专业版\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"考前模拟填报\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"投档线预测法择校\","
				+ "\"url\":\"getp.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"黄金录取线预测法择校\","
				+ "\"url\":\"get_hjx.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"名次法择校\","
				+ "\"url\":\"getp_mc.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"按专业择校\","
				+ "\"url\":\"getp_zy.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"心仪院校测算（名次预测）\","
				+ "\"url\":\"getp_xymc.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"心仪院校预测（分数测算）\","
				+ "\"url\":\"getp_xyfs.jsp\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"志愿模拟填报\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"考后智能填报\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"院校投档线预测\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"院校黄金录取线预测\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"院校专业录取线预测\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"按投档线择校\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"按黄金录取线择校\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"名次法择校\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"按专业择校\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"心仪院校测算（按名次）\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"心仪院校预测（按分数）\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"智能志愿填报\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"志愿表智能审核\","
				+ "\"url\":\"javascript:layer.msg('您的级别不够或者未到该功能的开放时间。', {title:'尊敬的用户', shade: 0.6, shadeClose: true, anim: 3});\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"报考课堂\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"电子书刊\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=1\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"视频讲座\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=2\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"实战指南\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=63&i&isQuery=1&isShowCnd=1&isAutoHideCnd=0&selCndID=lb&cnd_lb=3\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"代理管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"分级代理\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=85\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"公司级用户卡管理\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=84\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"代理商推广码\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"用户管理\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"专家服务管理\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=%3C%E5%A1%AB%E5%85%A5%E5%AD%90%E7%B3%BB%E7%BB%9F%E6%A0%87%E8%AF%86%3E&repID=%3C%E5%A1%AB%E5%85%A5%E6%8A%A5%E8%A1%A8%E6%A0%87%E8%AF%86%3E\","
				+ "\"target\":\"workspace\"}]},{"
				+ "\"name\": \"系统管理\","
				+ "\"arr\": ["
				+ "{"
				+ "\"name\": \"各省份充值设置\","
				+ "\"url\":\"/sysmng.report.do?subSys=gaokao&repID=88&isQuery=1&isShowCnd=1\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"在线帮助\","
				+ "\"url\":\"http://ly.9fsystem.com/sc.swf\","
				+ "\"target\":\"workspace\"},{"
				+ "\"name\": \"历年省控线\","
				+ "\"url\":\"http://gk.44m.cc/sysmng.report.do?subSys=gaokao&repID=37&isTopBar=0\","
				+ "\"target\":\"workspace\"}]}]";
	}
	return menuJson;
}